import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { darkTheme, lightTheme, themeToCss } from '@quickcaps/core';

const ALIASES = `:root {
  --surface: var(--background-100);
  --surface-raised: var(--gray-100);
  --border: var(--gray-400);
  --text-primary: var(--gray-1000);
  --text-secondary: var(--gray-800);
  --accent: var(--blue-600);
  --accent-hover: var(--blue-700);
  --error: var(--red-600);
  --warning: var(--amber-600);
  --success: var(--green-600);
  --radius-control: 6px;
  --radius-card: 8px;

  /* Spacing rhythm. One scale, so nothing is eyeballed. */
  --space-1: 4px;
  --space-2: 8px;
  --space-3: 12px;
  --space-4: 16px;
  --space-5: 24px;

  /* Motion. Short and eased-out: this is a tool, not a showreel. */
  --ease-out: cubic-bezier(0.16, 1, 0.3, 1);
  --duration-fast: 120ms;
  --duration-base: 180ms;
}
`;

function indent(css: string): string {
  return css
    .split('\n')
    .map((line) => (line ? `  ${line}` : line))
    .join('\n');
}

/**
 * Generated from core so the WCAG gate in core's theme test is checking the
 * same numbers the UI renders. Three theme states: the OS preference applies
 * by default, and an explicit data-theme wins in either direction.
 */
export function generateThemeCss(): string {
  return [
    '/* Generated by scripts/generate-theme-css.ts. Do not edit by hand. */',
    themeToCss(lightTheme, ':root'),
    `@media (prefers-color-scheme: dark) {\n${indent(
      themeToCss(darkTheme, ':root:not([data-theme="light"])'),
    )}}\n`,
    themeToCss(darkTheme, ':root[data-theme="dark"]'),
    ALIASES,
  ].join('\n');
}

if (process.argv[1]?.endsWith('generate-theme-css.ts')) {
  const target = join(
    dirname(fileURLToPath(import.meta.url)),
    '..',
    'src',
    'styles',
    'tokens.css',
  );
  writeFileSync(target, generateThemeCss(), 'utf8');
  console.log(`wrote ${target}`);
}
